#!/bin/bash

[[ -z $XP ]] && export XP=$HOME/.local/etc/profile.d
[[ -z $XH ]] && export XH=$HOME/.local/etc
[[ -d $XP ]] || mkdir -pv $XP
[[ -d $XH ]] || mkdir -pv $XH

cp ./{gpg_ssh.sh,nash.sh} $XP/
cp -r templates $XH/
